---
- name: Deploy Tomcat Application
  hosts: all
  tasks:
    - name: Copy WAR file to remote
      copy:
        src: /path/to/war/file/target/your-app-${artifact_version}.war
        dest: /path/to/remote/tomcat/webapps/your-app.war
    - name: Restart Tomcat
      service:
        name: tomcat
        state: restarted
